name: NeoLoad compare
on: 
  workflow_dispatch:
    inputs:
      guid1:
        required: true
        type: string
      guid2:
        required: true
        type: string
env:
  TEST_NAME: '"NeoloadPOC"'
  WORKSPACE_NAME: '"Evolution"'
  VERSION: '9.2.1'
  NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN }}
  ZONE: ${{ secrets.ZONE }}
  CREDENTIAL: ${{ secrets.CREDENTIAL }}


jobs:
  nightly_build_demo_app:
    name: Neoload POC
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - api_url: https://neoload-api.saas.neotys.com/
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Prepare Credentials
        run: |
          echo ${{ secrets.CREDENTIAL }} | base64 -d > ./nlweb.env
        
      - name: "Install NeoLoad CLI"
        run: pip3 install -U neoload
        
      - name: "NeoLoad Login"
        run: neoload login --url ${{ matrix.api_url }} --workspace ${{ env.WORKSPACE_NAME }} ${{ env.NEOLOADWEB_TOKEN }}
             
      - name: "Add Test1"
        run: neoload test-results use ${{ github.event.inputs.guid1 }}

      - name: "Add Test2"
        run: neoload test-results use ${{ github.event.inputs.guid2 }}

      - name: "Compare tests"
        run: neoload report --type=trends --template jinja/trends/transaction_trends.html.j2 --filter="results=${{ github.event.inputs.guid1 }}|${{ github.event.inputs.guid2 }}" --out-file transactions_trends.html

      - name: "Compare tests"
        run: neoload report --type=trends --template jinja/trends/general_details.html.j2 --filter="results=${{ github.event.inputs.guid1 }}|${{ github.event.inputs.guid2 }}" --out-file general_trends.html
         

      - name: "Upload All"
        uses: actions/upload-artifact@v3
        with:
          name: all
          path: |
            transactions_trends.html
            general_trends.html

 
