name: NeoLoad report
on: 
  workflow_dispatch:
    inputs:
      guid:
        required: true
        type: string
env:
  TEST_NAME: '"NeoloadPOC"'
  WORKSPACE_NAME: '"Evolution"'
  VERSION: '9.2.1'
  NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN }}
  ZONE: ${{ secrets.ZONE }}
  CREDENTIAL: ${{ secrets.CREDENTIAL }}


jobs:
  nightly_build_demo_app:
    name: Neoload POC
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - api_url: https://neoload-api.saas.neotys.com/
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Prepare Credentials
        run: |
          echo ${{ secrets.CREDENTIAL }} | base64 -d > ./nlweb.env
    
#       - name: "Start Controller and LGs"
#         run: docker-compose -f nlweb-infra-scale.yml up --detach --scale nlw-lg=2 --remove-orphans
      
#       - name: "Wait for infrastructure"
#         run: sleep 60
        
      - name: "Install NeoLoad CLI"
        run: pip3 install -U neoload
        
      - name: "NeoLoad Login"
        run: neoload login --url ${{ matrix.api_url }} --workspace ${{ env.WORKSPACE_NAME }} ${{ env.NEOLOADWEB_TOKEN }}
             
      - name: "Add Test"
        run: neoload test-results use ${{ github.event.inputs.guid }}
        
      - name: "Generate Raw data"
        run: neoload report --out-file raw_data_${{ github.event.inputs.guid }}.json
        
      - name: "Upload Raw data"
        uses: actions/upload-artifact@v3
        with:
          name: Raw_data
          path: raw_data_${{ github.event.inputs.guid }}.json
        
      - name: "Generate transaction data"
        run: neoload report --json-in raw_data_${{ github.event.inputs.guid }}.json --template builtin:transactions-csv --out-file transactions_${{ github.event.inputs.guid }}.csv
        
      - name: "Upload Transaction data"
        uses: actions/upload-artifact@v3
        with:
          name: transactions
          path: transactions_${{ github.event.inputs.guid }}.csv
          
      - name: "Generate HTML Report"
        run: neoload report --json-in raw_data_${{ github.event.inputs.guid }}.json --template jinja/sample-custom-report.html.j2 --out-file report_${{ github.event.inputs.guid }}.html
        
      - name: "Upload HTML Report"
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report_${{ github.event.inputs.guid }}.html


  - name: "Upload All"
        uses: actions/upload-artifact@v3
        with:
          name: all
          path: raw_data_${{ github.event.inputs.guid }}.json
          path: transactions_${{ github.event.inputs.guid }}.csv
          path: report_${{ github.event.inputs.guid }}.html

 
